import type { Category, EvidenceItem, EvidenceStatus, FileType, Tag } from "./types";

interface Seed {
  exhibitId: string;
  fileName: string;
  title: string;
  category: Category;
  subCategory: string;
  fileType: FileType;
  sizeKb: number;
  pageCount: number;
  status: EvidenceStatus;
  dateOfDocument: string;
  tags: Tag[];
  notes?: string;
  translation?: boolean;
}

const seeds: Seed[] = [
  {
    exhibitId: "Exhibit A-1",
    fileName: "petitioner_passport_bio_page.pdf",
    title: "Petitioner U.S. Passport Biographic Page",
    category: "Identity/Civil",
    subCategory: "Passport",
    fileType: "PDF",
    sizeKb: 1840,
    pageCount: 2,
    status: "Included in Final Packet",
    dateOfDocument: "2021-06-14",
    tags: ["#Critical", "#PrimaryEvidence"],
    notes: "Valid through 2031. Certified copy on file with counsel.",
  },
  {
    exhibitId: "Exhibit A-2",
    fileName: "beneficiary_birth_certificate.jpg",
    title: "Beneficiary Long-Form Birth Certificate",
    category: "Identity/Civil",
    subCategory: "Birth Record",
    fileType: "JPG",
    sizeKb: 3120,
    pageCount: 1,
    status: "Certified Translation Added",
    dateOfDocument: "1991-03-02",
    tags: ["#Critical", "#PrimaryEvidence"],
    notes: "Original in Bengali. Certified translation attached per 8 CFR 103.2(b)(3).",
    translation: true,
  },
  {
    exhibitId: "Exhibit A-3",
    fileName: "beneficiary_national_id.png",
    title: "Beneficiary National Identity Card",
    category: "Identity/Civil",
    subCategory: "Government ID",
    fileType: "PNG",
    sizeKb: 890,
    pageCount: 1,
    status: "Needs Translation",
    dateOfDocument: "2016-11-09",
    tags: ["#SecondaryEvidence", "#TranslationPending"],
  },
  {
    exhibitId: "Exhibit A-4",
    fileName: "name_change_deed_poll.pdf",
    title: "Deed Poll — Legal Name Change",
    category: "Identity/Civil",
    subCategory: "Name Change",
    fileType: "PDF",
    sizeKb: 640,
    pageCount: 3,
    status: "Reviewed & Ready",
    dateOfDocument: "2018-07-21",
    tags: ["#SecondaryEvidence"],
  },
  {
    exhibitId: "Exhibit A-5",
    fileName: "i94_travel_history.pdf",
    title: "I-94 Arrival/Departure Travel History",
    category: "Identity/Civil",
    subCategory: "Immigration Record",
    fileType: "PDF",
    sizeKb: 420,
    pageCount: 6,
    status: "Reviewed & Ready",
    dateOfDocument: "2025-01-30",
    tags: ["#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit A-6",
    fileName: "prior_visa_stamps.pdf",
    title: "Prior Nonimmigrant Visa Stamps Compilation",
    category: "Identity/Civil",
    subCategory: "Immigration Record",
    fileType: "PDF",
    sizeKb: 5210,
    pageCount: 14,
    status: "Draft",
    dateOfDocument: "2024-09-12",
    tags: ["#SecondaryEvidence"],
    notes: "Awaiting two missing pages from 2019 H-1B stamp.",
  },
  {
    exhibitId: "Exhibit B-1",
    fileName: "tax_return_2024.pdf",
    title: "2024 Form 1040 Joint Tax Return",
    category: "Financial/Tax",
    subCategory: "Federal Return",
    fileType: "PDF",
    sizeKb: 2380,
    pageCount: 42,
    status: "Included in Final Packet",
    dateOfDocument: "2025-04-11",
    tags: ["#Critical", "#JointAsset", "#PrimaryEvidence"],
    notes: "Filed jointly — strongest bona fide marriage indicator in the financial set.",
  },
  {
    exhibitId: "Exhibit B-2",
    fileName: "tax_return_2023.pdf",
    title: "2023 Form 1040 Joint Tax Return",
    category: "Financial/Tax",
    subCategory: "Federal Return",
    fileType: "PDF",
    sizeKb: 2210,
    pageCount: 38,
    status: "Included in Final Packet",
    dateOfDocument: "2024-04-09",
    tags: ["#JointAsset", "#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit B-3",
    fileName: "irs_tax_transcript_2024.pdf",
    title: "IRS Account Transcript — Tax Year 2024",
    category: "Financial/Tax",
    subCategory: "IRS Transcript",
    fileType: "PDF",
    sizeKb: 310,
    pageCount: 5,
    status: "Reviewed & Ready",
    dateOfDocument: "2025-05-02",
    tags: ["#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit B-4",
    fileName: "joint_bank_statements_2024.pdf",
    title: "Joint Checking Account Statements (Jan–Dec 2024)",
    category: "Financial/Tax",
    subCategory: "Bank Records",
    fileType: "PDF",
    sizeKb: 9120,
    pageCount: 64,
    status: "Reviewed & Ready",
    dateOfDocument: "2024-12-31",
    tags: ["#Critical", "#JointAsset"],
    notes: "Redact account numbers except last four before binding.",
  },
  {
    exhibitId: "Exhibit B-5",
    fileName: "mortgage_deed_joint.pdf",
    title: "Recorded Mortgage Deed — Both Spouses on Title",
    category: "Financial/Tax",
    subCategory: "Property",
    fileType: "PDF",
    sizeKb: 4400,
    pageCount: 22,
    status: "Reviewed & Ready",
    dateOfDocument: "2023-08-18",
    tags: ["#JointAsset", "#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit B-6",
    fileName: "life_insurance_beneficiary.pdf",
    title: "Life Insurance Policy Naming Spouse as Beneficiary",
    category: "Financial/Tax",
    subCategory: "Insurance",
    fileType: "PDF",
    sizeKb: 780,
    pageCount: 9,
    status: "Draft",
    dateOfDocument: "2024-02-27",
    tags: ["#JointAsset"],
  },
  {
    exhibitId: "Exhibit B-7",
    fileName: "w2_2024_petitioner.pdf",
    title: "2024 Form W-2 — Petitioner",
    category: "Financial/Tax",
    subCategory: "Wage Statement",
    fileType: "PDF",
    sizeKb: 180,
    pageCount: 2,
    status: "Reviewed & Ready",
    dateOfDocument: "2025-01-24",
    tags: ["#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit B-8",
    fileName: "foreign_bank_certificate.docx",
    title: "Foreign Bank Balance Certificate",
    category: "Financial/Tax",
    subCategory: "Bank Records",
    fileType: "DOCX",
    sizeKb: 96,
    pageCount: 2,
    status: "Needs Translation",
    dateOfDocument: "2025-03-14",
    tags: ["#TranslationPending", "#SecondaryEvidence"],
  },
  {
    exhibitId: "Exhibit B-9",
    fileName: "credit_card_joint_authorized_user.pdf",
    title: "Joint Credit Card — Authorized User Letter",
    category: "Financial/Tax",
    subCategory: "Credit",
    fileType: "PDF",
    sizeKb: 220,
    pageCount: 1,
    status: "Missing",
    dateOfDocument: "",
    tags: ["#JointAsset", "#RFERisk"],
    notes: "Requested from issuer 2026-08-22. No response yet — follow up weekly.",
  },
  {
    exhibitId: "Exhibit C-1",
    fileName: "employer_support_letter_cto.pdf",
    title: "Letter of Support — CTO, Northwind Systems",
    category: "Employment/Letters of Support",
    subCategory: "Expert Letter",
    fileType: "PDF",
    sizeKb: 340,
    pageCount: 4,
    status: "Included in Final Packet",
    dateOfDocument: "2026-05-19",
    tags: ["#Critical", "#PrimaryEvidence"],
    notes: "Signed on letterhead. Addresses national importance prong directly.",
  },
  {
    exhibitId: "Exhibit C-2",
    fileName: "independent_expert_letter_stanford.pdf",
    title: "Independent Expert Letter — Prof. A. Reyes, Stanford",
    category: "Employment/Letters of Support",
    subCategory: "Expert Letter",
    fileType: "PDF",
    sizeKb: 410,
    pageCount: 5,
    status: "Reviewed & Ready",
    dateOfDocument: "2026-06-03",
    tags: ["#Critical", "#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit C-3",
    fileName: "employment_verification_letter.pdf",
    title: "Employment Verification Letter with Salary History",
    category: "Employment/Letters of Support",
    subCategory: "HR Verification",
    fileType: "PDF",
    sizeKb: 190,
    pageCount: 2,
    status: "Reviewed & Ready",
    dateOfDocument: "2026-07-01",
    tags: ["#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit C-4",
    fileName: "resume_cv_current.docx",
    title: "Beneficiary Curriculum Vitae (Current)",
    category: "Employment/Letters of Support",
    subCategory: "CV",
    fileType: "DOCX",
    sizeKb: 74,
    pageCount: 7,
    status: "Draft",
    dateOfDocument: "2026-08-15",
    tags: ["#SecondaryEvidence"],
    notes: "Convert to PDF/A before final packet compilation.",
  },
  {
    exhibitId: "Exhibit C-5",
    fileName: "citation_report_scholar.pdf",
    title: "Independent Citation Report — 412 Citations",
    category: "Employment/Letters of Support",
    subCategory: "Impact Evidence",
    fileType: "PDF",
    sizeKb: 1520,
    pageCount: 18,
    status: "Reviewed & Ready",
    dateOfDocument: "2026-08-02",
    tags: ["#Critical", "#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit C-6",
    fileName: "conference_invitation_keynote.pdf",
    title: "Keynote Invitation — IEEE Systems Summit",
    category: "Employment/Letters of Support",
    subCategory: "Recognition",
    fileType: "PDF",
    sizeKb: 260,
    pageCount: 2,
    status: "Draft",
    dateOfDocument: "2026-04-28",
    tags: ["#SecondaryEvidence"],
  },
  {
    exhibitId: "Exhibit C-7",
    fileName: "peer_review_invitations.pdf",
    title: "Journal Peer Review Invitations (Compiled)",
    category: "Employment/Letters of Support",
    subCategory: "Recognition",
    fileType: "PDF",
    sizeKb: 980,
    pageCount: 11,
    status: "Draft",
    dateOfDocument: "2026-03-17",
    tags: ["#SecondaryEvidence"],
  },
  {
    exhibitId: "Exhibit C-8",
    fileName: "prior_employer_letter_translated.pdf",
    title: "Prior Employer Letter — Overseas Role",
    category: "Employment/Letters of Support",
    subCategory: "HR Verification",
    fileType: "PDF",
    sizeKb: 300,
    pageCount: 3,
    status: "Certified Translation Added",
    dateOfDocument: "2019-10-04",
    tags: ["#SecondaryEvidence"],
    translation: true,
  },
  {
    exhibitId: "Exhibit D-1",
    fileName: "marriage_certificate_certified.pdf",
    title: "Certified Marriage Certificate",
    category: "Proof of Relationship",
    subCategory: "Marriage Record",
    fileType: "PDF",
    sizeKb: 1120,
    pageCount: 2,
    status: "Included in Final Packet",
    dateOfDocument: "2020-02-14",
    tags: ["#Critical", "#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit D-2",
    fileName: "joint_lease_agreement.pdf",
    title: "Joint Residential Lease Agreement",
    category: "Proof of Relationship",
    subCategory: "Cohabitation",
    fileType: "PDF",
    sizeKb: 2640,
    pageCount: 26,
    status: "Reviewed & Ready",
    dateOfDocument: "2022-05-01",
    tags: ["#JointAsset", "#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit D-3",
    fileName: "wedding_photos_compilation.pdf",
    title: "Annotated Wedding & Family Photo Compilation",
    category: "Proof of Relationship",
    subCategory: "Photographs",
    fileType: "PDF",
    sizeKb: 14200,
    pageCount: 31,
    status: "Reviewed & Ready",
    dateOfDocument: "2020-02-16",
    tags: ["#SecondaryEvidence"],
    notes: "Each photo captioned with date, location, and persons pictured.",
  },
  {
    exhibitId: "Exhibit D-4",
    fileName: "joint_utility_bills_2025.pdf",
    title: "Joint Utility Bills (12 Months, 2025)",
    category: "Proof of Relationship",
    subCategory: "Cohabitation",
    fileType: "PDF",
    sizeKb: 3400,
    pageCount: 24,
    status: "Reviewed & Ready",
    dateOfDocument: "2025-12-20",
    tags: ["#JointAsset"],
  },
  {
    exhibitId: "Exhibit D-5",
    fileName: "affidavit_of_support_friend.docx",
    title: "Third-Party Affidavit of Bona Fide Marriage — J. Okafor",
    category: "Proof of Relationship",
    subCategory: "Affidavit",
    fileType: "DOCX",
    sizeKb: 58,
    pageCount: 3,
    status: "Draft",
    dateOfDocument: "2026-07-19",
    tags: ["#SecondaryEvidence"],
    notes: "Needs notarization before it can move to legal review.",
  },
  {
    exhibitId: "Exhibit D-6",
    fileName: "child_birth_certificate.jpg",
    title: "Child's Birth Certificate Listing Both Parents",
    category: "Proof of Relationship",
    subCategory: "Birth Record",
    fileType: "JPG",
    sizeKb: 2760,
    pageCount: 1,
    status: "Reviewed & Ready",
    dateOfDocument: "2022-09-08",
    tags: ["#Critical", "#PrimaryEvidence"],
  },
  {
    exhibitId: "Exhibit D-7",
    fileName: "travel_itineraries_together.pdf",
    title: "Joint Travel Itineraries & Boarding Passes",
    category: "Proof of Relationship",
    subCategory: "Travel",
    fileType: "PDF",
    sizeKb: 1980,
    pageCount: 17,
    status: "Draft",
    dateOfDocument: "2025-11-02",
    tags: ["#SecondaryEvidence"],
  },
  {
    exhibitId: "Exhibit D-8",
    fileName: "foreign_family_register.png",
    title: "Foreign Family Register Extract",
    category: "Proof of Relationship",
    subCategory: "Civil Register",
    fileType: "PNG",
    sizeKb: 1440,
    pageCount: 2,
    status: "Needs Translation",
    dateOfDocument: "2021-01-25",
    tags: ["#TranslationPending", "#RFERisk"],
  },
  {
    exhibitId: "Exhibit E-1",
    fileName: "divorce_decree_prior_marriage.pdf",
    title: "Final Divorce Decree — Prior Marriage",
    category: "Legal/Court Records",
    subCategory: "Court Order",
    fileType: "PDF",
    sizeKb: 900,
    pageCount: 8,
    status: "Certified Translation Added",
    dateOfDocument: "2017-06-30",
    tags: ["#Critical", "#PrimaryEvidence"],
    translation: true,
    notes: "Termination of prior marriage — mandatory for I-130 eligibility.",
  },
  {
    exhibitId: "Exhibit E-2",
    fileName: "police_clearance_certificate.pdf",
    title: "Police Clearance Certificate — Home Country",
    category: "Legal/Court Records",
    subCategory: "Background Check",
    fileType: "PDF",
    sizeKb: 410,
    pageCount: 2,
    status: "Needs Translation",
    dateOfDocument: "2026-06-11",
    tags: ["#TranslationPending"],
  },
  {
    exhibitId: "Exhibit E-3",
    fileName: "court_disposition_dismissed.pdf",
    title: "Certified Court Disposition — Charge Dismissed",
    category: "Legal/Court Records",
    subCategory: "Court Order",
    fileType: "PDF",
    sizeKb: 320,
    pageCount: 4,
    status: "Reviewed & Ready",
    dateOfDocument: "2015-04-22",
    tags: ["#RFERisk", "#PrimaryEvidence"],
    notes: "Include counsel memo explaining no admission of guilt.",
  },
  {
    exhibitId: "Exhibit E-4",
    fileName: "attorney_g28_signed.pdf",
    title: "Form G-28 Notice of Attorney Appearance",
    category: "Legal/Court Records",
    subCategory: "USCIS Form",
    fileType: "PDF",
    sizeKb: 240,
    pageCount: 2,
    status: "Included in Final Packet",
    dateOfDocument: "2026-08-30",
    tags: ["#Critical"],
  },
  {
    exhibitId: "Exhibit E-5",
    fileName: "sworn_affidavit_translator.pdf",
    title: "Translator Certification Affidavit (Blanket)",
    category: "Legal/Court Records",
    subCategory: "Affidavit",
    fileType: "PDF",
    sizeKb: 150,
    pageCount: 1,
    status: "Reviewed & Ready",
    dateOfDocument: "2026-07-27",
    tags: ["#SecondaryEvidence"],
  },
  {
    exhibitId: "Exhibit F-1",
    fileName: "i693_medical_sealed.pdf",
    title: "Form I-693 Medical Examination (Sealed Copy Record)",
    category: "Medical/Vaccination",
    subCategory: "Medical Exam",
    fileType: "PDF",
    sizeKb: 1260,
    pageCount: 12,
    status: "Draft",
    dateOfDocument: "2026-08-25",
    tags: ["#Critical"],
    notes: "Civil surgeon sealed envelope — do not open. Log only.",
  },
  {
    exhibitId: "Exhibit F-2",
    fileName: "vaccination_record_childhood.jpg",
    title: "Childhood Vaccination Record",
    category: "Medical/Vaccination",
    subCategory: "Immunization",
    fileType: "JPG",
    sizeKb: 1680,
    pageCount: 2,
    status: "Needs Translation",
    dateOfDocument: "2003-05-17",
    tags: ["#TranslationPending", "#SecondaryEvidence"],
  },
  {
    exhibitId: "Exhibit F-3",
    fileName: "tb_test_results.pdf",
    title: "IGRA Tuberculosis Test Results",
    category: "Medical/Vaccination",
    subCategory: "Lab Result",
    fileType: "PDF",
    sizeKb: 210,
    pageCount: 1,
    status: "Reviewed & Ready",
    dateOfDocument: "2026-08-12",
    tags: ["#SecondaryEvidence"],
  },
  {
    exhibitId: "Exhibit F-4",
    fileName: "vaccination_waiver_request.docx",
    title: "Religious Vaccination Waiver Request Draft",
    category: "Medical/Vaccination",
    subCategory: "Waiver",
    fileType: "DOCX",
    sizeKb: 42,
    pageCount: 3,
    status: "Missing",
    dateOfDocument: "",
    tags: ["#RFERisk"],
    notes: "Only required if the civil surgeon flags an outstanding vaccine.",
  },
];

const ACTORS = ["A. Whitfield (Counsel)", "Paralegal Desk", "Drive Sync", "Client Upload"];

function buildAudit(index: number, item: Omit<EvidenceItem, "auditTrail">): EvidenceItem["auditTrail"] {
  const base = new Date(Date.UTC(2026, 5, 1 + (index % 25), 9 + (index % 8), (index * 7) % 60));
  const entries = [
    { action: `Synced from Drive as ${item.fileName}`, actor: "Drive Sync" },
    { action: `Assigned ${item.exhibitId} and categorized under ${item.category}`, actor: ACTORS[index % ACTORS.length] },
    { action: `Status set to ${item.status}`, actor: "A. Whitfield (Counsel)" },
  ];
  return entries.map((entry, i) => ({
    id: `${item.id}-audit-${i}`,
    at: new Date(base.getTime() + i * 1000 * 60 * 60 * 26).toISOString(),
    actor: entry.actor,
    action: entry.action,
  }));
}

export const mockEvidence: EvidenceItem[] = seeds.map((seed, index) => {
  const id = `ev-${String(index + 1).padStart(3, "0")}`;
  const base: Omit<EvidenceItem, "auditTrail"> = {
    id,
    exhibitId: seed.exhibitId,
    fileName: seed.fileName,
    title: seed.title,
    category: seed.category,
    subCategory: seed.subCategory,
    fileType: seed.fileType,
    fileSizeBytes: seed.sizeKb * 1024,
    pageCount: seed.pageCount,
    status: seed.status,
    dateOfDocument: seed.dateOfDocument,
    tags: seed.tags,
    cloudDriveUrl: `https://drive.google.com/file/d/mock-${id}/view`,
    translationFileUrl: seed.translation
      ? `https://drive.google.com/file/d/mock-${id}-translation/view`
      : undefined,
    notes: seed.notes ?? "",
  };
  return { ...base, auditTrail: buildAudit(index, base) };
});
