/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDiaryExtractRouteImport } from './routes/api/diary-extract'
import { Route as ApiPublicGcCloneTickRouteImport } from './routes/api/public/gc-clone-tick'
import { Route as ApiPublicGcFinanceRebuildRouteImport } from './routes/api/public/gc-finance-rebuild'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiaryExtractRoute = ApiDiaryExtractRouteImport.update({
  id: '/api/diary-extract',
  path: '/api/diary-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGcCloneTickRoute = ApiPublicGcCloneTickRouteImport.update({
  id: '/api/public/gc-clone-tick',
  path: '/api/public/gc-clone-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGcFinanceRebuildRoute =
  ApiPublicGcFinanceRebuildRouteImport.update({
    id: '/api/public/gc-finance-rebuild',
    path: '/api/public/gc-finance-rebuild',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/diary-extract': typeof ApiDiaryExtractRoute
  '/api/public/gc-clone-tick': typeof ApiPublicGcCloneTickRoute
  '/api/public/gc-finance-rebuild': typeof ApiPublicGcFinanceRebuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/diary-extract': typeof ApiDiaryExtractRoute
  '/api/public/gc-clone-tick': typeof ApiPublicGcCloneTickRoute
  '/api/public/gc-finance-rebuild': typeof ApiPublicGcFinanceRebuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/diary-extract': typeof ApiDiaryExtractRoute
  '/api/public/gc-clone-tick': typeof ApiPublicGcCloneTickRoute
  '/api/public/gc-finance-rebuild': typeof ApiPublicGcFinanceRebuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/diary-extract'
    | '/api/public/gc-clone-tick'
    | '/api/public/gc-finance-rebuild'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/diary-extract'
    | '/api/public/gc-clone-tick'
    | '/api/public/gc-finance-rebuild'
  id:
    | '__root__'
    | '/'
    | '/api/diary-extract'
    | '/api/public/gc-clone-tick'
    | '/api/public/gc-finance-rebuild'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDiaryExtractRoute: typeof ApiDiaryExtractRoute
  ApiPublicGcCloneTickRoute: typeof ApiPublicGcCloneTickRoute
  ApiPublicGcFinanceRebuildRoute: typeof ApiPublicGcFinanceRebuildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diary-extract': {
      id: '/api/diary-extract'
      path: '/api/diary-extract'
      fullPath: '/api/diary-extract'
      preLoaderRoute: typeof ApiDiaryExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gc-clone-tick': {
      id: '/api/public/gc-clone-tick'
      path: '/api/public/gc-clone-tick'
      fullPath: '/api/public/gc-clone-tick'
      preLoaderRoute: typeof ApiPublicGcCloneTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gc-finance-rebuild': {
      id: '/api/public/gc-finance-rebuild'
      path: '/api/public/gc-finance-rebuild'
      fullPath: '/api/public/gc-finance-rebuild'
      preLoaderRoute: typeof ApiPublicGcFinanceRebuildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDiaryExtractRoute: ApiDiaryExtractRoute,
  ApiPublicGcCloneTickRoute: ApiPublicGcCloneTickRoute,
  ApiPublicGcFinanceRebuildRoute: ApiPublicGcFinanceRebuildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
